### ISSUE TITLE
dependency on react-broadcast?

### ISSUE THREAD

**Issue by ehahn9** [drcmda/react-contextual#10]
Is there really a dependency on `react-broadcast` (seen in `package.json` but maybe not in the implementation)?

**Comment by drcmda** [comment]
@ehahn9 Only until react 16.4.0 is out, which will be shortly. You can already update to react@next/react-dom@next and it'll use native context. If you need it i can release a @next as well without broadcast in it.

**Comment by ehahn9** [comment]
Thanks @drcmda! I'm still at the investigation phase, so I'd hate to make any work for you - no need to do anything about the dependency!

`react-contextual` seems like a GREAT alternative to `unstated` which is getting a lot of airplay.

**Comment by drcmda** [comment]
@ehahn9 Thanks! Unstated follows a similar idea, but doesn't consider the performance hit of context. Without mapContextToProps in a real world application everything will render on everything.
