### ISSUE TITLE
server side render support?

### ISSUE THREAD

**Issue by hardfist** [drcmda/react-contextual#12]
It seems that the library doesn't support server side render support, I can't get props from store in subscribe components in server side render

**Comment by drcmda** [comment]
@hardfist Do you know what it should do in order to support it? I have not much experience with SSR.

**Comment by drcmda** [comment]
@hardfist 
Actually, i looked over everything again and i'm pretty sure now that Reacts server renderer simply isn't equipped for the new context api yet. It should start working by itself. You might try it with react@next and react-dom@next as well, there's a good chance they've already completed it.

**Comment by hardfist** [comment]
@drcmda  sorry,It seems that I make something wrong, It works perfectly on SSR!
