### ISSUE TITLE
Context not triggering subscriptions / triggering with undefined.

### ISSUE THREAD

**Issue by MauriceButler** [drcmda/react-contextual#19]
I havnt had the chance to look into this deeper but a simple example of subscribing to 2 stores is failing.

sample code https://codesandbox.io/s/n3yok829n4

If you click the up and downs buttons it will not render correctly and sometimes throw due to an undefined store being passed to the mapStateToProps function.

Ill try to dig into it and find a cause tomorrow but if there is something you can see I am doing incorrectly please set me straight :smile:

**Comment by drcmda** [comment]
@MauriceButler thanks for notifying, i'm on it: https://github.com/facebook/react/issues/12604

**Comment by drcmda** [comment]
Looks like a React bug now. A workaround is going back to react/react-dom @16.4.0-alpha.3174632. I hope they'll fix it.

**Comment by drcmda** [comment]
@MauriceButler it's fixed in 4.0.4, see here: https://codesandbox.io/s/7212l1qjlj

Something in React changed between the last alpha and the 16.3.1 release. I adapted the pattern i use to collect providers, i hope this should be it.

**Comment by MauriceButler** [comment]
Thanks @drcmda not bad to raise and issue, have it upstreamed, discussed and fixed before I wake up 😛
