### ISSUE TITLE
React component tree renders <Unknown> wrappers

### ISSUE THREAD

**Issue by amite** [drcmda/react-contextual#7]
Was playing around with the async example: https://codesandbox.io/embed/lxly45lvkl on localhost and noticed this in my React Dev Tools:

<img width="1378" alt="screen shot 2018-02-23 at 9 22 23 am" src="https://user-images.githubusercontent.com/1308947/36577134-5ce822e8-187b-11e8-96d5-e1992e4f168d.png">

There are two unknown Components rendering which wrap `ToolBar` and `Content`. Why is that? 🧐

**Comment by drcmda** [comment]
@amite  This happens why you export anonomous (unnamed) components, which the hoc's were. See: https://stackoverflow.com/questions/43458971/react-dev-tools-show-my-component-as-unknown

I made an update (3.8.3) and named them: SubscribeWrapper, ModuleContext, NamedContext and TransformContext.

**Comment by amite** [comment]
Understood 👌
