### ISSUE TITLE
Warning: <Consumer> was rendered outside the context of its <Provider> 

### ISSUE THREAD

**Issue by JJLost** [drcmda/react-contextual#9]
These examples arent exactly a direct comparison but:
[Warning with Decorators](https://codesandbox.io/s/l41xwkr5kq)
[No Warning with Components](https://codesandbox.io/s/l4j5l9w0zm)

I have scenarios in my application where certain contexts are optional. 

Is this warning expected behavior?  I would prefer to remove warnings before production.

**Comment by drcmda** [comment]
They're from React/react-broadcast and until now expected. Curious if they're also in the upcoming release i updated your box to react@next and react-dom@next (1.6.4-alpha) then the warnings seem to disappear: https://codesandbox.io/s/3yplp3pqqm 

It remains to be seen if they have them in the next release. Technically a consumer outside a provider doesn't make much sense, though. At most it could receive a default value, the one you can provide as second argument to the context creation hocs: 

    @namedContext(props => props.id, "hello world")
    class ...
